config/routes.rb
Rails.application.routes.draw do
  resources :plusrs
  resources :plans
  resources :users
  resources :adcoms
  resources :companies
  resources :admins

end

app/models/plusr.rb
class Plusr < ActiveRecord::Base
  belongs_to :plan
  belongs_to :user
end

app/controllers/plusrs_controller.rb
class PlusrsController < ApplicationController
  before_action :set_plusr, only: [:show, :edit, :update, :destroy]

  # GET /plusrs
  # GET /plusrs.json
  def index
    @plusrs = Plusr.all
  end

  # GET /plusrs/1
  # GET /plusrs/1.json
  def show
  end

  # GET /plusrs/new
  def new
    @plusr = Plusr.new
  end

  # GET /plusrs/1/edit
  def edit
  end

  # POST /plusrs
  # POST /plusrs.json
  def create
    @plusr = Plusr.new(plusr_params)

    respond_to do |format|
      if @plusr.save
        format.html { redirect_to @plusr, notice: 'Plusr was successfully created.' }
        format.json { render :show, status: :created, location: @plusr }
      else
        format.html { render :new }
        format.json { render json: @plusr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plusrs/1
  # PATCH/PUT /plusrs/1.json
  def update
    respond_to do |format|
      if @plusr.update(plusr_params)
        format.html { redirect_to @plusr, notice: 'Plusr was successfully updated.' }
        format.json { render :show, status: :ok, location: @plusr }
      else
        format.html { render :edit }
        format.json { render json: @plusr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plusrs/1
  # DELETE /plusrs/1.json
  def destroy
    @plusr.destroy
    respond_to do |format|
      format.html { redirect_to plusrs_url, notice: 'Plusr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plusr
      @plusr = Plusr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plusr_params
      params.require(:plusr).permit(:plan_id, :user_id)
    end
end

app/helpers/plusrs_helper.rb
module PlusrsHelper
end

app/views/plusrs/_form.html.erb
<%= form_for(@plusr) do |f| %>
  <% if @plusr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plusr.errors.count, "error") %> prohibited this plusr from being saved:</h2>

      <ul>
      <% @plusr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plan_id %><br>
    <%= f.text_field :plan_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plusrs/edit.html.erb
<h1>Editing Plusr</h1>

<%= render 'form' %>

<%= link_to 'Show', @plusr %> |
<%= link_to 'Back', plusrs_path %>

app/views/plusrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plusrs</h1>

<table>
  <thead>
    <tr>
      <th>Plan</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plusrs.each do |plusr| %>
      <tr>
        <td><%= plusr.plan %></td>
        <td><%= plusr.user %></td>
        <td><%= link_to 'Show', plusr %></td>
        <td><%= link_to 'Edit', edit_plusr_path(plusr) %></td>
        <td><%= link_to 'Destroy', plusr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plusr', new_plusr_path %>

app/views/plusrs/new.html.erb
<h1>New Plusr</h1>

<%= render 'form' %>

<%= link_to 'Back', plusrs_path %>

app/views/plusrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plan:</strong>
  <%= @plusr.plan %>
</p>

<p>
  <strong>User:</strong>
  <%= @plusr.user %>
</p>

<%= link_to 'Edit', edit_plusr_path(@plusr) %> |
<%= link_to 'Back', plusrs_path %>